CREATE TABLE STUDENTS(
	STUID INT,
	FIRSTNAME VARCHAR(25),
	LASTNAME VARCHAR(25),
	WEBSITE VARCHAR(50),
	CITY VARCHAR(25),
	DIVISION VARCHAR(20)
	)

	SELECT * FROM STUDENTS
	--Q1.
	SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'K%'
	--Q2.
	SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE '_____'
	--Q3.
	SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE CITY LIKE '_____a'
	--Q4.
	SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%TEL'
	--Q5.
	SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'HA%T'
	--Q6.
	SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'K_Y%'
	--Q7.
	SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'
	--Q8.
	SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '%JER%'
	--Q9.
	SELECT * FROM STUDENTS WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'
	--Q10.
	SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE IS NOT NULL
	--Q11.
	SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '[A-H]%'
	--Q12.
	SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%'
	--Q13.
	SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE CITY LIKE '%ROD%'
	--Q14.
	SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE WEBSITE LIKE 'BI%'
	--Q15.
	SELECT CITY FROM STUDENTS WHERE LASTNAME LIKE '______'
	--Q16.
	SELECT * FROM STUDENTS WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%'
	--Q17.
	SELECT * FROM STUDENTS WHERE DIVISION LIKE 'II%'
	--Q18.
	SELECT FIRSTNAME FROM STUDENTS WHERE DIVISION LIKE '%BC%'
	--Q19.
	SELECT STUID,CITY FROM STUDENTS WHERE DIVISION LIKE '______' AND WEBSITE IS NOT NULL
	--Q20.
	SELECT * FROM STUDENTS WHERE FIRSTNAME NOT LIKE '__[A,E,I,O,U]%' 

















































	
